---
- name: Manage Postfix installation
  hosts: test
  become: yes
  tasks:
    - name: Install Postfix
      ansible.builtin.package:
        name: postfix
        state: present
      tags: init

    - name: Ensure Postfix is running and enabled
      ansible.builtin.service:
        name: postfix
        state: started
        enabled: yes
      tags: init

    - name: Remove Postfix
      ansible.builtin.package:
        name: postfix
        state: absent
      tags: drop

    - name: Stop and disable Postfix service
      ansible.builtin.service:
        name: postfix
        state: stopped
        enabled: no
      tags: drop
