---
- name: Install vsftpd
  ansible.builtin.package:
    name: vsftpd
    state: present

- name: Configure vsftpd
  ansible.builtin.template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd.conf
  notify: Restart vsftpd

- name: Ensure vsftpd is running and enabled
  ansible.builtin.service:
    name: vsftpd
    state: started
    enabled: yes
