---
- name: Install php-fpm
  apt:
    name: php-fpm
    state: present
    update_cache: yes

- name: Configure php-fpm to listen on port 9000
  lineinfile:
    path: /etc/php/8.3/fpm/pool.d/www.conf
    regexp: '^listen = '
    line: 'listen = 127.0.0.1:9000'
  notify:
    - Restart php-fpm

- name: Start and enable php-fpm service
  service:
    name: php8.3-fpm
    state: started
    enabled: yes
